### ISSUE TITLE
[Announcement] dnx-watch

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dotnet-watch#10]
Discussions for https://github.com/aspnet/Announcements/issues/74

**Comment by runxc1** [comment]
Will this work with beta7 or do we need to wait till beta8 comes out?

**Comment by dmccaffery** [comment]
THANK... YOU! :+1: :+1:

**Comment by victorhurdugaci** [comment]
@runxc1 you need beta8

**Comment by rhwy** [comment]
oh oh cool! (then my own dnx-watcher working on mono/mac will be now useless  and I won't have to maintain it ;-)

**Comment by dmccaffery** [comment]
haha. I wrote one too; theres one build into the https://github.com/pulsebridge/condo build system (dnx run).

**Comment by rhwy** [comment]
mine was mainly a wrapper around https://github.com/rhwy/fswatcher from acken that allows me to watch files on macosx (because the -watch from dnx, well..., never worked), but it only worked on dnx451 and not core, btw I didn't knew condo, will have a look, seems great

**Comment by dmccaffery** [comment]
It's new; not well documented...yet; I'm working on it, but I don't want to hijack this thread; if you have any questions, feel free to ping me here on github or Twitter.

**Comment by kamranayub** [comment]
Is this planned to just roll into `dnx --watch`? I was just bitten by that, new user.

**Comment by victorhurdugaci** [comment]
`dnx --watch` is going awai. `dnx-watch` is the replacement

**Comment by victorhurdugaci** [comment]
Closing this issue because `dnx-watch` went away. The new command is `dotnet-watch`
