### ISSUE TITLE
dotnet-watch --command test - MissingMethodException

### ISSUE THREAD

**Issue by rdefreitas** [aspnet/dotnet-watch#100]
I'm attempting to run tests in core RC2. My test project does not have an entry point (Program.cs) and runs tests properly using the command "`dotnet test`".

I'm not sure if it would be better to address this issue here or in xunit. I created an issue there as well: xunit/xunit#849

When I try to run tests continuously, however, I see the following error:

	H:\Dev\Sample\test\Sample.Test.Unit>dotnet watch --command test
	[DotNetWatcher] info: Running dotnet with the following arguments: run -- --command test
	[DotNetWatcher] info: dotnet process id: 572048
	Project Sample (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
	Project Sample.Test.Unit (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
	Compiling Sample.Test.Unit for .NETCoreApp,Version=v1.0
	Compilation succeeded.
	0 Warning(s)
	0 Error(s)
	Time elapsed 00:00:01.7921147

	Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'Sample.Test.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	[DotNetWatcher] fail: dotnet exit code: -532462766

My project.json contains these entries:

	{
		"version": "1.0.0-*",
		"testRunner": "xunit",
		"dependencies": {
			"Sample": { "target": "project" },
			"dotnet-test-xunit": "1.0.0-rc2-*",
			"xunit": "2.1.0",
			"Microsoft.DotNet.Watcher.Tools": {
				"version": "1.0.0-preview1-final",
				"type": "build"
			}
		},
		"frameworks": {
			"netcoreapp1.0": {
				"dependencies": {
					"Microsoft.NETCore.App": {
						"type": "platform",
						"version": "1.0.0-*"
					}
				},
				"imports": [
					"dnxcore50",
					"portable-net45+win8"
				]
			}
		},
		"tools": {
			"Microsoft.DotNet.Watcher.Tools": {
				"version": "1.0.0-preview1-final",
				"imports": "portable-net451+win8"
			}
		}
	}

**Comment by victorhurdugaci** [comment]
You're hitting one of the weird cases of dotnet watch. We have a lot of processes involved in the watcher chain (dotnet -> watch -> dotnet -> command) and there's some of confusion around what argument gets passed to which process.

dotnet watch <anything other than --help or -- > runsdotnet run -- <all arguments> (yes, dotnet run has it's own -- argument and we special cased it). So, dotnet watch --command test becomes dotnet run -- --command test (you can see that in the console output) which means that --command test is passed to the app being executed by dotnet run.

If you want to pass any arguments to the watcher, you have to use --:

dotnet watch --command test -- runsdotnet test
dotnet watch --command test -- -parallel none runsdotnet test -parallel none
The first -- is the separator between the watcher arguments and watched app arguments.

**Comment by rdefreitas** [comment]
I see. This isn't really clearly documented, and the asp.net docs don't say anything about this.

I see this case as pretty common, instead of running `dotnet watch --command test --` with those extra hyphens, since the test runner is a built-in and needed feature, can there be a special case added such that someone could just run `dotnet watch test`?

**Comment by CoreyKaylor** [comment]
Agreed regarding this being pretty common. Good that there's at least a way that works, but it should stay simple to cater for the common case of `dotnet watch test`

**Comment by CoreyKaylor** [comment]
Also I'm seeing the examples that pass arguments to the test runner probably won't work either. https://github.com/dotnet/cli/issues/1385

**Comment by victorhurdugaci** [comment]
We'll consider special casing `test` since it's a first class property in `project.json` and I'll make sure the docs are up to date.

As for the other issue, it seems that that's an xunit issue... `dotnet run -- --foo` passes `--foo` to the compiled application

**Comment by victorhurdugaci** [comment]
We'll track this issue [here](https://github.com/aspnet/dotnet-watch/issues/105). Closing this one
