### ISSUE TITLE
Rename environment variable used to enable polling

### ISSUE THREAD

**Issue by mikeharder** [aspnet/dotnet-watch#101]
Both dotnet-watch and MVC use environment variables to enable polling.  Currently, dotnet-watch uses `USE_POLLING_FILE_WATCHER`, while MVC uses `ASPNETCORE_POLL_FOR_FILE_CHANGES`.  To simplify things for customers, including the Dockerfile generated by Docker for VS Tooling, we would like to use the same variable for both dotnet-watch and MVC, and name it accordingly.

Related: https://github.com/aspnet/Mvc/issues/4696

**Comment by muratg** [comment]
@Eilon Can we agree on a name? @victorhurdugaci will do the change both here and on https://github.com/aspnet/Mvc/issues/4696 

cc @pranavkm

**Comment by mikeharder** [comment]
Existing names:

```
USE_POLLING_FILE_WATCHER (dotnet-watch)
ASPNETCORE_POLL_FOR_FILE_CHANGES (mvc)
```

Proposals for unified name:

```
WATCHER_POLL_FOR_FILE_CHANGES
WATCHER_USE_POLLING
NETCORE_POLL_FOR_FILE_CHANGES
```

**Comment by muratg** [comment]
`DOTNET_USE_POLLING_FILE_WATCHER`?

**Comment by Eilon** [comment]
Yeah I dig that name.

**Comment by Eilon** [comment]
That is, the name that @muratg suggested.

**Comment by muratg** [comment]
@victorhurdugaci please update it both here and in MVC.
