### ISSUE TITLE
dotnet watch on net451 - Could not load type 'System.ICloneable'

### ISSUE THREAD

**Issue by guylando** [aspnet/dotnet-watch#103]
I have an asp.net 5 project running using the cli but targets net451 framework.
When trying to run dotnet watch it says the following and does not continue: 

[DotNetWatcher] fail: Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
[DotNetWatcher] info: Fix the error to continue.

From the research I done about System.ICloneable I think this occurs because the dotnet watch package is using cross platform libraries which do not support System.ICloneable (http://stackoverflow.com/a/23060851/5386197) while net451 DOES use System.ICloneable.

How can I run dotnet watch on an application with net451 target framework?

I have in my project.json:
...
"tools": {
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-preview1-21005",
      "imports": "net451"
    }
  },
  "frameworks": {
    "net451": {
    }
  }
...

**Comment by victorhurdugaci** [comment]
You shouldn't change the imports for dotnet watch. If you want to run an application for a different framework then you have to pass the `--framework net451` argument to `dotnet run`:

`dotnet watch --command run -- --framework net451 --` 
or
`dotnet watch --command run -- --framework net451 -- <args>` 

We know that argument passing is a bit confusing. We'll update the docs.

**Comment by guylando** [comment]
Still same error.

I changed project.json as you said to:
"tools": {
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-preview1-21006",
      "imports": "portable-net451+win8"
    }
  }

My project.lock.json has:
"tools": {
    ".NETCoreApp,Version=v1.0": {
      "Microsoft.DotNet.Watcher.Tools/1.0.0-preview1-21006": {
        "type": "package",
        "dependencies": {
          "Microsoft.DotNet.Watcher.Core": "1.0.0-preview1-21006",
          "Microsoft.Extensions.CommandLineUtils": "1.0.0-rc3-21006",
          "Microsoft.Extensions.Logging": "1.0.0-rc3-21006",
          "Microsoft.Extensions.Logging.Console": "1.0.0-rc3-21006",
          "Microsoft.NETCore.App": "1.0.0-rc2-3002702"
        },
        "compile": {
          "lib/netcoreapp1.0/dotnet-watch.dll": {}
        },
        "runtime": {
          "lib/netcoreapp1.0/dotnet-watch.dll": {}
        }
      }
    }
  },
  "projectFileToolGroups": {
    ".NETCoreApp,Version=v1.0": [
      "Microsoft.DotNet.Watcher.Tools >= 1.0.0-preview1-21006"
    ]
  }

And I tried to run:
dotnet -v watch --command run --framework net451
and
dotnet -v watch --command run -- --framework net451

And I still get the same error.

**Comment by guylando** [comment]
My guess is that the problem is that a net451 program with an mscrolib that has ICloneable is trying to compile a netcoreapp1.0 program (dotnet watch) which has an app mscrolib without ICloneable

**Comment by guylando** [comment]
This is what it says before the error occures when running with -v:

Running C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\XXX\.nuget\packages\.tools\Microsoft.DotNet.Watcher.Tools\1.0.0-preview1-21006\netcoreapp1.0\Microsoft.DotNet.Watcher.Tools.deps.json --additionalprobingpath C:\Users\XXX\.nuget\packages C:\Users\XXX\.nuget\packages\Microsoft.DotNet.Watcher.Tools\1.0.0 -preview1-21006\lib\netcoreapp1.0\dotnet-watch.dll --command run --framework net451

And then the error which aborts it.

**Comment by davidfowl** [comment]
These imports are incorrect:

```
"imports": "net451"
```

You shouldn't change the imports of the tool, that's incorrect.

**Comment by guylando** [comment]
Thanks for the help.
Changing the "imports" back to "portable-net451+win8" did not help solve the problem (see my previous comment) because it seems that previous version was still used.
What finally solved the problem was after changing the imports, I deleted the watcher packages both from C:\Users\XXX\.nuget\packages and from C:\Users\Guy\.nuget\packages\.tools and then done a dotnet restore and the watcher started working.
