### ISSUE TITLE
Simplify watcher arguments proposal

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dotnet-watch#105]
Proposed changes:

- Remove `--exit-on-change` (confirmed that it's not used by anyone internally)
- Remove `--command`
- All arguments are passed to dotnet (except `--help`. That's special and shows watcher help).

Examples:

- I want to show help
    - Before: `dotnet watch --help`
    - After: `dotnet watch` or `dotnet watch --help`
- I want to run `dotnet run`
    - Before: `dotnet watch` or `dotnet watch --command run --`
    - After: `dotnet watch run` 
- I want to run `dotnet run -- --arg1 value`
    - Before `dotnet watch --arg1 value` or `dotnet watch --command run -- -- --arg1 value` (yes, double `--`)
    - After: `dotnet watch run -- --arg1 value`
- I want to run `dotnet run --framework net451 --`
    - Before: `dotnet watch --command run -- --framework net451 --`
    - After: `dotnet watch run --framework net451 --`
- I want to run `dotnet test`
    - Before: `dotnet watch --command test --`
    - After: `dotnet watch test`
- I want to run` dotnet test -parallel none`
    - Before: `dotnet watch --command test -- -parallel none`
    - After: `dotnet watch test -parallel none` 

Pros:
- You don't need to learn special syntax for watch. Just add `watch` after `dotnet`. So `dotnet <args>` becomes `dotnet watch <args>`
- No more confusion about what gets passed to dotnet watch

Cons:
- `dotnet watch` shows help.
- You need to specify `run` if you want `dotnet run`
- You cannot pass `--help` to the app being watched

cc @glennc

**Comment by moozzyk** [comment]
_I want to run dotnet run
Before: dotnet watch or dotnet watch --command run --
After: dotnet run_

Shouldn't after be `dotnet watch run`?

**Comment by victorhurdugaci** [comment]
Yes, fixed :)

**Comment by victorhurdugaci** [comment]
@Eilon and @glennc what do you think about doing this now?

**Comment by rdefreitas** [comment]
I would propose that `dotnet watch` with no arguments should still execute `dotnet run`, as this feels a bit more like other watchers. (even though they require explicit configuration).

**Comment by victorhurdugaci** [comment]
That's a tricky one because `dotnet watch` would run `dotnet run` while `dotnet watch --foo` would run `dotnet --foo`. I think most folks would expect `dotnet --foo` to be `dotnet run --foo` in that case.

**Comment by Eilon** [comment]
Done?

**Comment by victorhurdugaci** [comment]
Done :)

**Comment by Eilon** [comment]
4-Thanks!
