### ISSUE TITLE
Why do we need to modify project.json

### ISSUE THREAD

**Issue by jchannon** [aspnet/dotnet-watch#111]
Hi, having used nodemon in the past that watches javascript files and restarts the server with no config required to the actual app why does dnx watch need it. Is there a way to use dnx watch without modifying my app's project.json file?

**Comment by cmatskas** [comment]
@jchannon raises a valid point and would be nice to know why we changed the mechanics around the `watch` command. Could you guys add a response below or point us to a blog post with details around this decision. It feels a lot more invasive than in other modern languages/frameworks

**Comment by miguellira** [comment]
This issue was opened after a Twitter thread among this group earlier today...

Of course by "dnx" @jchannon means "dotnet". I guess a different way to ask the same thing is: As a first class "tool" for .NET core, what advantages do you gain from using `dotnet-watch` over another watcher.

**Comment by victorhurdugaci** [comment]
In the `dnx` world we had global commands that you could install globally without having to change `project.json`. However, you couldn't add them as a dependency to `project.json`, so you couldn't restore them globally.

In the `dotnet` world, things changed. There's no global acquisition story for tools, but now tools are at least added to `project.json` so they can be restored.

I agree that `dotnet watch` and some other tools that we ship could be standalone apps but we don't have a nice acquisition story for such apps, yet. In fact, `dotnet watch` (and other `dotnet` commands) are regular applications. If you get the source code, you can `dotnet run` it.

The advantage of `dotnet watch` over a generic file watcher is that `dotnet watch` understands `project.json` and doesn't trigger on non code files changes. For example, if you exclude a cs file from compilation, then the watcher will not trigger when that file changes. Another example is view files: we know that MVC will handle view file changes so we don't restart when those files change.

Also, `dotnet watch` knows how to watch code changes in referenced projects and even packages that are replaced by sources, even when they are outside of your solution's folder.

**Comment by miguellira** [comment]
@victorhurdugaci That's for thorough and clear response.

**Comment by victorhurdugaci** [comment]
I'm going to assume that my answer was sufficient and close the issue. Please reopen if that's not the case.
