### ISSUE TITLE
dotnet watch test does not run unit tests

### ISSUE THREAD

**Issue by danielsaidi** [aspnet/dotnet-watch#113]
Hi,

I am porting a lib to .NET Core and are currently writing unit tests for it.

When I run `dotnet test`, the tests run as expected. However, when I run `dotnet watch test`, I get the following:

```
[DotNetWatcher] info: Running dotnet with the following arguments: run -- test
[DotNetWatcher] info: dotnet process id: 61181
Project XXX (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hello, World!
[DotNetWatcher] info: dotnet exit code: 0
[DotNetWatcher] info: Waiting for a file to change before restarting dotnet...
```

It seems dotnet watch runs the project instead of running the tests.

**Comment by victorhurdugaci** [comment]
If you're using RC2 bits, the command line syntax is: https://github.com/aspnet/dotnet-watch/blob/release/README.md
If you're using RC3 bits, the command line syntax is: https://github.com/aspnet/dotnet-watch/blob/dev/README.md

Based on you're log, I think you're using RC2. So, to run `dotnet test` run `dotnet watch --command test --`

**Comment by danielsaidi** [comment]
Yeah, you're right in that I'm using RC2, and the line you posted worked. Thanks a million!
