### ISSUE TITLE
Configure dotnet watch via config file and setup multiple commands

### ISSUE THREAD

**Issue by tmds** [aspnet/dotnet-watch#114]
I have a project with a gulp watch to check for typescript changes and a dotnet watch for aspnet core changes.

It would be nice if I could run a single watcher and set it up with a config file.

Relates to: https://github.com/aspnet/dotnet-watch/issues/87, https://github.com/aspnet/dotnet-watch/issues/32

**Comment by victorhurdugaci** [comment]
Thanks for the suggestion! We'll address this as part of https://github.com/aspnet/dotnet-watch/issues/87

**Comment by natemcmaster** [comment]
This is now "supported". The "config file" is the MSBuild project. You can configure custom targets and custom watch items using MSbuild.

You can configure custom watch items using the `Watch` item group. See the README for more details.

```xml
<ItemGroup>
    <!-- extends watching group to include *.js files -->
    <Watch Include="**\*.js" Exclude="node_modules\**\*.js;$(DefaultExcludes)" />
</ItemGroup>
```

See https://github.com/aspnet/DotNetTools/issues/87 for example of how to configure custom commands.
