### ISSUE TITLE
3 tests broken

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dotnet-watch#117]
GlobbingAppTests.ChangeCompiledFile_PollingWatcher
GlobbingAppTests.ChangeNonCompiledFile_DotNetWatcher
GlobbingAppTests.ChangeNonCompiledFile_PollingWatcher
These broke from one of your recent changes I'm guessing @victorhurdugaci

**Comment by victorhurdugaci** [comment]
This should be fixed. Pushed by mistake directly to dev: https://github.com/aspnet/dotnet-watch/commit/c5abb2e2ebdc73d7814d09aae56490fdb32921b2
