### ISSUE TITLE
Should dotnet-watch be able to run commands other than run?

### ISSUE THREAD

**Issue by davidMuir** [aspnet/dotnet-watch#124]
Currently trying to use dotnet watch to just build on file changes

I'm using dotnet watch as follows:

```
dotnet watch build
```

and expecting the following command to be run

```
dotnet build
```

the command that is actually ran is 
```
dotnet run --build
```

Is there any way to get this behaviour?

**Comment by victorhurdugaci** [comment]
If you're using RC2 bits, the command line syntax is: https://github.com/aspnet/dotnet-watch/blob/release/README.md
If you're using RC3 bits, the command line syntax is: https://github.com/aspnet/dotnet-watch/blob/dev/README.md

Based on your log, I think you're using RC2. So, to run `dotnet build` run `dotnet watch --command build --`. For RC3, you'd run, as you expect, `dotnet watch build`

**Comment by davidMuir** [comment]
Yep that's done it!

Thanks for the help, and for creating such a useful tool!
