### ISSUE TITLE
Dotnet watch run has error output and success output for F# project

### ISSUE THREAD

**Issue by sokket** [aspnet/dotnet-watch#127]
# Steps
1) Make a new F# project directory
2) Restore
3) Run ```dotnet watch run```

# Expected
Success!

# Actual

Both success and error outputs

[bb@bb-oraclelinux72 F#]$ ../../dotnet/dotnet watch run
[DotNetWatcher] info: Running dotnet with the following arguments: run -- run
[DotNetWatcher] info: dotnet process id: 19909
Project F# (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling F# for .NETCoreApp,Version=v1.0
No executable found matching command "dotnet-compile-fsc"
Compilation failed.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.0790970
/home/bb/dotnet/dotnet compile-fsc @/home/bb/global/F#/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
[DotNetWatcher] fail: dotnet exit code: 1
[DotNetWatcher] info: Waiting for a file to change before restarting dotnet...

**Comment by victorhurdugaci** [comment]
> No executable found matching command "dotnet-compile-fsc"

Why do you think this is a watcher issue? Does it work without "watch"?

**Comment by sokket** [comment]
Yes, running ```dotnet run``` worked perfectly fine

**Comment by victorhurdugaci** [comment]
Interesting... `dotnet watch run` simply calls `dotnet run`. I'll take a look

**Comment by victorhurdugaci** [comment]
@sokket is this even supported? It seems that the latest CLI doesn't have F# support. Even when running an app without watcher, I get `No executable found matching command "dotnet-compile-fsc"` and it seems that indeed `dotnet-compile-fsc` is not on disk

**Comment by sokket** [comment]
`dotnet run` for F# is supported...if watch doesn't support F# then feel free to close this issue :). 

Which version of the CLI and from which channel?

**Comment by victorhurdugaci** [comment]
watch it language agnostic. It starts a process calling `dotnet run`.

I'm using the RTM CLI (1.0.0-preview2-003121)

**Comment by victorhurdugaci** [comment]
Tried 1.0.0-preview3-003150 and still no fsc

**Comment by sokket** [comment]
@piotrpMSFT Any ideas why fsc isn't there?

**Comment by victorhurdugaci** [comment]
hey @sokket , I'm not able to reproduce the issue. It seems that everything works:

```bash
E:\temp\Foo1
> dotnet restore
log  : Restoring packages for E:\temp\Foo1\project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in E:\temp\Foo1\project.json...
log  : Restoring packages for tool 'dotnet-compile-fsc' in E:\temp\Foo1\project.json...
log  : Writing lock file to disk. Path: E:\temp\Foo1\project.lock.json
log  : E:\temp\Foo1\project.json
log  : Restore completed in 4699ms.

E:\temp\Foo1
> dotnet watch run
[DotNetWatcher] info: Running dotnet with the following arguments: run
[DotNetWatcher] info: dotnet process id: 12448
Project Foo1 (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling Foo1 for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:06.3892526

Hello World!
[||]
[DotNetWatcher] info: dotnet exit code: 0
[DotNetWatcher] info: Waiting for a file to change before restarting dotnet...
[DotNetWatcher] info: Running dotnet with the following arguments: run
[DotNetWatcher] info: dotnet process id: 19364
Project Foo1 (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling Foo1 for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:06.4856223

Hello World!
[||]
[DotNetWatcher] info: dotnet exit code: 0
[DotNetWatcher] info: Waiting for a file to change before restarting dotnet...
```

Can you please try it with the latest dotnet watch and see if you can still repro? From your original log it seems that you were using the rc1 version.

**Comment by victorhurdugaci** [comment]
@sokket as per our offline conversation, please reopen if you can still repro.
