### ISSUE TITLE
Console colors are lost during watching (Windows)

### ISSUE THREAD

**Issue by Ciantic** [aspnet/dotnet-watch#135]
System: Windows 10, 64bit

I have ILogger that prints colors by default e.g. `fail` is red when ran like `dotnet run` but the colors stops working if I run it in watch mode `dotnet watch run`

**Comment by BrennanConroy** [comment]
Known issue see https://github.com/dotnet/cli/issues/1977#issuecomment-227214885
Should be fixed in the latest CLI, or one that will be built soon
