### ISSUE TITLE
Watch with Debugging

### ISSUE THREAD

**Issue by tysonnero** [aspnet/dotnet-watch#141]
I've tried to add a new command to my project.json as follow:
```
"commands": {
    "Watcher Development": "dotnet watch run"
  },
```
The command gets added to my Run profile dropdown, however, when I run Watcher Development, the usual dot net watch console output doesn't occur as opposed to when I run dotnet watch run completely from command line and my breakpoints no longer hit if i change code.

Any thoughts?

**Comment by victorhurdugaci** [comment]
The `commands` section in `project.json` is `dnx` specific. `dotnet` doesn't support it. Because `dotnet watch` is for `dotnet`, mixing the two is not supported.

**Comment by victorhurdugaci** [comment]
PS: if VS still understands it and you're running on the latest VS, it might be a bug in the tooling

**Comment by tysonnero** [comment]
@victorhurdugaci Thanks for the heads up on that. Is there any way to run `dotnet watch run` from within VS with debugging?

**Comment by victorhurdugaci** [comment]
It might be possible to do it from the NuGet console but I never tried that. Otherwise, you'll need an external console.
