### ISSUE TITLE
Color coded console output is not maintained

### ISSUE THREAD

**Issue by NotMyself** [aspnet/dotnet-watch#144]
I have a project that writes to the console with color coded text. When run with the watch command the color coding is stripped out. 

Here is an example:
![screen shot 2016-07-21 at 5 48 25 pm](https://cloud.githubusercontent.com/assets/73120/17043459/acba0316-4f6b-11e6-93fe-14783afe6f4a.png)

**Comment by NotMyself** [comment]
Looks like `Console.Clear()` is not respected either...

**Comment by victorhurdugaci** [comment]
Known issue in `preview2` https://github.com/dotnet/cli/issues/1977 should be fixed in the latest CLI.

Please reopen if you can still reproduce with the latest dev bits.

cc @BrennanConroy
