### ISSUE TITLE
Port fixes to tests to rel/1.0.1 branch

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dotnet-watch#145]
@victorhurdugaci made a change to (https://github.com/aspnet/dotnet-watch/commit/21b35259332877ef60730971a8d1a28b99e63475) to workaround a known flakiness in the file watcher. This issue seems to be cropping up very consistently on OSX when building the patch branch. The fix here would be to produce a rel/1.0.1 branch of https://github.com/aspnet/dotnet-watch based on 1.0.0 and backport this change.

cc @muratg \ @Eilon \ @BrennanConroy

**Comment by Eilon** [comment]
Please send email to me and @DamianEdwards to discuss and approve.

**Comment by Eilon** [comment]
Oh wait sorry. This was just the test thing.

**Comment by Eilon** [comment]
Yeah let's create a branch for it. But keep all the versions 1.0.0. Just need the branch + test fix, no other changes as far as I know. No approval needed.
