### ISSUE TITLE
Updated for RTM?

### ISSUE THREAD

**Issue by tonysneed** [aspnet/dotnet-watch#149]
Has this been updated for RTM?  It seems to work with RC2 of the DotNet CLI SDK, but not with the current version (preview2).

**Comment by nickolasacosta** [comment]
make sure you dotnet restore before trying :)

**Comment by tonysneed** [comment]
Actually, I discovered that the problem was that I did not have the correction version in the tools section of project.json.  It should be:

```json
  "tools": {
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-preview2-final"
    }
  }
```
