### ISSUE TITLE
Auto refresh browser

### ISSUE THREAD

**Issue by irashid25** [aspnet/dotnet-watch#150]
Hi all,

I'm using dotnet watch with my asp.net core MVC app and I have it working so that it automatically builds when I save a file. Is there a way to automatically refresh the browser so I can see the results without having to manually click F5?.

Thanks

**Comment by victorhurdugaci** [comment]
Hi @irashid25,

There's no way to auto refresh the browser. `dotnet-watch` is not web specific, thus it doesn't know anything about the environment in which the app runs. We might consider extensions in the future, but right now there's no way to do that.

**Comment by irashid25** [comment]
Thanks for the quick reply victor.

I think I can get it done by using gulp and the visual studio task runner. I could set off a gulp task to reload the browser using browser sync etc after the project has been built.

Will try it tonight.

Thanks
