### ISSUE TITLE
dotnet-watch does not watch *.cshtml files

### ISSUE THREAD

**Issue by jsouthron** [aspnet/dotnet-watch#152]
It appears when running the below command that razor view files are not being watched.  

`C:\solution_directory\ dotnet watch run `

Is this expected behavior, or am I doing something wrong on my side?  Also it appears in general that my solution requires a rebuild before razor files are updated in the browser.  This is supremely frustrating.  
```

{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "BundlerMinifier.Core": "2.2.281"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by dougbu** [comment]
MVC internally watches the `*.cshtml` files referenced in a site and reloads them if they change. Don't need to restart the application for this.

If you are changing files and not seeing changes reflected in responses from the site, might be worth checking you're touching the files your app is viewing. That can be different from what you expect in some publish scenarios.

@BrennanConroy am I correct that `dotnet-watch` checks only the `"buildOptions": { "compile": "..." }` files and whatever the legacy `project.json` setting was? Modulo the default globs of course.

**Comment by victorhurdugaci** [comment]
`dotnet watch` watches code files, embedded resources, preprocessor files (legacy) and shared code files. View files are not in that list because, like @dougbu said, they're compiled by Razor and the process doesn't have to be restarted to reflect the changes.

**Comment by jsouthron** [comment]
I suppose this is probably the wrong forum for this.  When I change razor files, the changes do not appear in the browser.  I know I am touching the same file, because there only is one file in the project.  This has been the case ever since I have been working with .netcore projects.  I assume I am just missing something fundamental here.

**Comment by dougbu** [comment]
@jsouthron please file your issue in the MVC repo -- https://github.com/aspnet/Mvc I suggest describing how you're running the site and changing the files in the new issue.

Side note: `Areas/**/Views` in `"publishOptions": { "include": [ ... ] }` doesn't work correctly. Switch that to `**/*.cshtml`. I doubt this relates to the current issue but may help you later.

**Comment by jsouthron** [comment]
Thanks Doug I opened it under http://github.com/aspnet/RavorTooling I will cross post at MVC.

**Comment by muratg** [comment]
Thanks @jsouthron! Looks like dotnet watch behaves as expected in this case. Closing this one.

**Comment by natemcmaster** [comment]
@rynowak @pranavkm - should we revisit this default for 2.1? Does the new Razor SDK disable runtime compilation in development in favor of pre-compiled views?

**Comment by pranavkm** [comment]
Mvc still does runtime compilation if views change, so the original premise has remain unchanged. @KhalilMohammad could you share more details about how \ where you're generating your pdf files?

**Comment by KhalilMohammad** [comment]
I think this issue more related to [https://github.com/aspnet/RazorTooling/issues/121](IRazorViewEngine does not pick updated cshtml)
