### ISSUE TITLE
Support MSBuild v15.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dotnet-watch#156]
project.json and Microsoft.DotNet.ProjectModel are being retired in favor of xplat MSBuild. dotnet-watch should update to support the new project system for dotnet-cli.

Open questions

 - How should we interpret the project system to discover files to watch? Two options:
    1. Make dotnet-watch an msbuild task
    2. Host MSBuild and execute a design-time build to discover items and properties
 - Can we ensure we detect files are added when MSBuild uses globs?
 - Can we reuse components from https://github.com/dotnet/roslyn-project-system to do this?

**Comment by victorhurdugaci** [comment]
A note on "Make dotnet-watch an msbuild task": this might or might not work depending on what msbuild does. If dotnet-watch is running as part of msbuild, then msbuild might lock the project file. That means that you'll not be able to update it.

**Comment by natemcmaster** [comment]
Closing as dup of #161
