### ISSUE TITLE
files included in the project with "compile" are not watched

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dotnet-watch#19]
If I add files to the project.json using `compile` (e.g. `"compile": [ "../../../DnxLib/src/DnxLib/Class.cs" ],`) they are not being watched - i.e. the target process is not restarted if the included file changes.

Same applies to files specified in `resource` (e.g. "resource": [ "project.json_" ],)

**Comment by muratg** [comment]
@victorhurdugaci We had a discussion on this but I don't remember the outcome.  Is this something we can make work properly?

**Comment by jpoehls** [comment]
FWIW this is affecting one of my projects. Specifically the `resource` files not being watched. My scenario is the following:

- `dnx-watch` is monitoring `./web-project/project.json`
- `./web-project/project.json` references another project in the same solution, `./class-library/project.json`.
- `./class-library/project.json` includes Razor views as embedded resources in the `resource` section of `project.json`.

I'm expecting `dnx-watch` to restart if it detects those resource files change in the class library project that is referenced by the web project being watched.
