### ISSUE TITLE
dnx-watch hangs after Ctrl+C on Mono Mac OS

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dotnet-watch#22]
Ctrl+C does not terminate dnx-watch on Mono or Mac OS. Changes to files no longer trigger restarting the target process. The process has to be killed. 

(Note: this seems to work fine on Linux)

**Comment by muratg** [comment]
@victorhurdugaci Could you please investigate?

**Comment by victorhurdugaci** [comment]
If this is happening only on Mono then it will not longer be an issue with `dotnet-watch` since it only runs on CoreCLR

**Comment by cottsak** [comment]
I can't get this to work on Windows using cmder either. :disappointed:

**Comment by victorhurdugaci** [comment]
@cottsak what doesn't work?

**Comment by cottsak** [comment]
@victorhurdugaci CTRL+C doesn't interrupt `dnx-watch` on Windows using cmder.

**Comment by victorhurdugaci** [comment]
Okay, I'll give it a try tomorrow. If you run the same scenario in a normal console does it work? Also, let me know what version of dnx and dnx-watch you're using.
