### ISSUE TITLE
dnx-watch is not notified when the extension of the file changes to an ignored extension

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dotnet-watch#23]
If you rename a file that is being watched to have an extension that is ignored (e.g. `Program.cs` :arrow_right: `Program.vb`) dnx-watch does not restart the target process. (Changing the extension from an ignored one to watched does trigger the restart)

**Comment by victorhurdugaci** [comment]
Known issue. It has the same limitation as `dnx --watch`
