### ISSUE TITLE
FileSystemWatcher error handling

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dotnet-watch#24]
Observation from nosing around your code:

I've used FileSystemWatcher in the past and had great trouble with it erroring, going into a broken state and it no longer reporting changes. An example of this happening is watching a network share path, the network connection gets interrupted, and FileSystemWatcher errors and then permanently breaks.

The way I fixed this was using its Error event. When it errored I created a new FileSystemWatcher instance, copied the events and properties across, started it and disposed of the broken FileSystemWatcher.

Something to think about and test.

**Comment by JamesNK** [comment]
Example: http://stackoverflow.com/questions/6184115/filesystemwatcher-stops-catching-events

**Comment by muratg** [comment]
Let's investigate.

**Comment by muratg** [comment]
@victorhurdugaci After your partial rewrite, is this still an issue?

**Comment by victorhurdugaci** [comment]
I haven't seen any issues with the watcher not triggering or Error-ing on CoreCLR. I'll close the issue for now
