### ISSUE TITLE
Notification on watch

### ISSUE THREAD

**Issue by Antaris** [aspnet/dotnet-watch#32]
Is it possible to integrate a platform-specific notification for when the app is restarted with watch? Ala Grunt/Gulp-notify?

**Comment by victorhurdugaci** [comment]
Currently that's not possible but we're considering it for a future release.

**Comment by jasoncavett** [comment]
This would be great to have. Then it can easily be integrated into other processes and pipelines (e.g. minification, SASS complication, browser-sync, etc).

**Comment by victorhurdugaci** [comment]
This will be addressed as part of https://github.com/aspnet/dotnet-watch/issues/87 because you'll be able to start your own command that can do notifications.
