### ISSUE TITLE
Evaluate globbing patterns on watch

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dotnet-watch#4]
Today we ignore the globbing patterns in project.json

The watcher should include/exclude files based on them

**Comment by muratg** [comment]
Let's consider this as part of the dotnet update.

**Comment by victorhurdugaci** [comment]
This became important because there are some scenarios in which dotnet build drops a cs file in the obj folder and the watcher restarts instantly, even before running the app.
