### ISSUE TITLE
DNX-WATCH crashes on Docker machine

### ISSUE THREAD

**Issue by AlexChesser** [aspnet/dotnet-watch#40]
Using a yeoman generator from the latest (rc1) aspnet web application template site.
Specifically using the following docker file:

```
FROM microsoft/aspnet
# add sqlite3 to ensure database crash doesn't happen
RUN printf "deb http://ftp.us.debian.org/debian jessie main\n" >> /etc/apt/sources.list
RUN apt-get -qq update && apt-get install -qqy sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /code
# install DNX watcher and add to PATH
RUN dnu commands install Microsoft.Dnx.Watcher
ENV PATH $PATH:/root/.dnx/bin

# ensure packages are installed on server before code is build to speed reload times
COPY ./WebApplication/project.json /code/project.json
RUN ["dnu","restore"]
# add the rest of the code - lightning fast rebuilds if dependencies are unchanged.
COPY ./WebApplication /code

EXPOSE 5000
### All of the following fail:
# ENTRYPOINT ["dnx-watch" ]
# ENTRYPOINT ["dnx-watch", "web" ]
# ENTRYPOINT ["dnx-watch", "web", "-p", "project.json" ]
# ENTRYPOINT ["dnx-watch", "--project", "project.json", "web", "-p", "project.json" ]
# ENTRYPOINT ["dnx-watch", "--project", "project.json" ]
# ENTRYPOINT ["dnx-watch", "--project", "project.json", "web" ]
### this one DOES work:
ENTRYPOINT ["dnx", "web" ]
```

Any of the commented-out entry points exit with the error:

```
PS C:\Users\Alex\www\aspnet-docker> docker build -t aspnet-localdev .
[ ... lots of stuff happens here, but is eventually successful ... ]
PS C:\Users\Alex\www\aspnet-docker> docker run -itP aspnet-localdev
exec format error
Error response from daemon: Cannot start container 57368f0929af6d66a18b173cbf5ab8614a67e3ffe51a0937e1d97c9dd7d76139: [8] System error: exec format error
PS C:\Users\Alex\www\aspnet-docker>
```
note additionally if I run the command:
```
PS C:\Users\Alex\www\aspnet-docker> docker run -itP aspnet-localdev bash
```
I can execute `dnx-watch` within the shell and see *something* happen. (this only works if the container can start up, so the entrypoint must be ` ["dnx", "web" ]` or blank.

**Comment by AlexChesser** [comment]
it appears to be a known issue in ubuntu http://askubuntu.com/a/697757
as the dnx-watch command as located in `/root/.dnx/bin` *does* appear to be a link to another file (I don't have the system in front of me right now, but it is something like `/packages.../DnxWatcher/.../bin`) ... if I try to chagedir to the path listed in the file I receive errors. 

It might be as simple as updating the path to the linked location?

**Comment by muratg** [comment]
@glennc did you get a chance to look into this yet?

**Comment by glennc** [comment]
Haven't completely forgotten about this. Waiting for the current churn around changing this to `dotnet-watch` and then I will try and reproduce, make sure it isn't still a problem after all the changes.

**Comment by AlexChesser** [comment]
Thanks for the update!  I figure it's a bit of a pain for you lot right now.

**Comment by victorhurdugaci** [comment]
`dotnet-watch` should work on docker. If you can still reproduce the issue, please reopen
