### ISSUE TITLE
DnxWatcher fail

### ISSUE THREAD

**Issue by lmxin123** [aspnet/dotnet-watch#59]
This is my cmd log:
E:\OneDrive\work\codes\Mycode\Lmxin.ChongZhi>dnvm use 1.0.0-rc1-update1
Adding C:\Users\Katana\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin to process PATH
E:\OneDrive\work\codes\Mycode\Lmxin.ChongZhi>dnx-watch
[DnxWatcher] info: Running dnx with the following arguments: --project E:\OneDrive\work\codes\Mycode\Lmxin.ChongZhi\project.json
[DnxWatcher] info: dnx process id: 10728
Microsoft .NET Execution environment Clr-x86-1.0.0-rc1-16231

Usage: dnx [options]

Options:
  --project|-p <PATH>              Path to the project.json file or the application folder. Defaults to the current folder if not provided.
  --appbase <PATH>                 Application base directory path
  --lib <LIB_PATHS>                Paths used for library look-up
  --debug                          Waits for the debugger to attach before beginning execution.
  --bootstrapper-debug             Waits for the debugger to attach before bootstrapping runtime.
  --framework <FRAMEWORK_ID>       Set the framework version to use when running (i.e. dnx451, dnx452, dnx46, ...)
  -?|-h|--help                     Show help information
  --version                        Show version information
  --watch                          Watch file changes
  --packages <PACKAGE_DIR>         Directory containing packages
  --configuration <CONFIGURATION>  The configuration to run under
  --port <PORT>                    The port to the compilation server
[DnxWatcher] fail: dnx exit code: 2
[DnxWatcher] info: Waiting for a file to change before restarting dnx...
--------------------------------------------------------------------------------------------------------
**I don't know where the problem is.**

**Comment by muratg** [comment]
Does your app run fine without the watcher?

**Comment by victorhurdugaci** [comment]
What `dnx-watch` version do you use?

**Comment by lmxin123** [comment]
@muratg yes,It run fine without the watcher.
@victorhurdugaci my dnx-watch version is 1.0.0-rc1-final.

**Comment by victorhurdugaci** [comment]
Ah, I just noticed what you're missing. You need to specify the command from `project.json` to run. The commands are in the `commands` section.

**Comment by moozzyk** [comment]
exit code 2 means that no parameters were provided to a dnx command

**Comment by muratg** [comment]
@lmxin123 Let us know if you still have issues!

**Comment by lmxin123** [comment]
@victorhurdugaci Thank you very much! I update like this
  "commands": {
    "web": "Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
    "ef": "EntityFramework.Commands",
    "dnx-watch":"run"
  };
It run well.

**Comment by victorhurdugaci** [comment]
1. `dnx-watch` should not be a command in `project.json`
2. @Tratcher I remember seeing an issue a few days ago where you helped someone with that error (`EnsureServer`). What was the fix? 

Btw, now you're hitting a hosting error.

**Comment by Tratcher** [comment]
use `web` instead of `run`

**Comment by lmxin123** [comment]
Good,it run well,Thank you!
