### ISSUE TITLE
Dotnet watch doesn't restart on OSX because of a corefx issue

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dotnet-watch#67]
Caused by https://github.com/dotnet/corefx/issues/7680

If it doesn't get fixed on their side, we need to workaround it.

cc @glennc

**Comment by glennc** [comment]
This is a tracking issue.

If it is fixed in corefx for RC2 then we can close this. If not then we will need to workaround the issue for RC2 and then back out the changes for the release after RC2.

**Comment by muratg** [comment]
@victorhurdugaci Please follow-up the rel check-in & our CoreFX consumption in the CI

**Comment by victorhurdugaci** [comment]
Fixed by the latest CoreFx
