### ISSUE TITLE
Application doesn't get restarted on changes to some files (example: Views)

### ISSUE THREAD

**Issue by kichalla** [aspnet/dotnet-watch#89]
**Scenario:**
Using VS Code to work with MusicStore repo and using 'dotnet watch' to watch the application. Any updates to Views, controllers etc. should trigger an automatic restart of the application.

**Repro**
- Clone MusicStore repo and checkout the Release branch.
- Open the `project.json` file under `src\MusicStore` and add the following setting to the `buildOptions` node (this kind of change is required in all our repos after recent schema change, but that's a different discussion)
```
    "copyToOutput": {
      "include": [
        "Areas",
        "Views",
        "wwwroot",
        "config.json",
        "web.config"
      ]
    }
```
- `dotnet restore` at `src\musicstore` folder
- `dotnet watch`
- Make a change to `HomeController.cs` file's `Index` action and you should see the change picked up
- Make a change to `Views\Home\Index.cshtml` (example: change the title of the view) and you should see that it does not trigger any restart

**Expected:**
The changes to view files are picked up and the application is restarted.

**Actual:**
Changes are not picked up. I do not see any activity (i.e any log statements about dotnet watch knowing about a file change).

However any changes to the `.cs` files in the project are picked up as expected.

@victorhurdugaci @muratg

**Comment by victorhurdugaci** [comment]
Changes to views are not supposed to be picked up by dotnet watch; that's by design because:
1. Dotnet watch only watches code file changes
2. Dotnet watch has no concept of views, it's not an ASPNET web watcher
3. MVC will recompile the views

**Comment by victorhurdugaci** [comment]
Where's the list of scenarios?

**Comment by kichalla** [comment]
> Where's the list of scenarios?

Yes, I am getting at it.

> MVC will recompile the views so the process should not restart

But wondering how would this ever work though. During development I would be modifying the view files that are present in my project folder and not the ones that have already been copied to the build output.

@pranavkm @davidfowl

**Comment by victorhurdugaci** [comment]
> kichalla commented 4 hours ago

Did you comment on this at 4AM? :confused: 

> But wondering how would this ever work though. During development I would be modifying the view files that are present in my project folder and not the ones that have already been copied to the build output.

That's a different problem. You should be able to specify somehow that the views should be loaded from a different folder.

**Comment by kichalla** [comment]
> That's a different problem. You should be able to specify somehow that the views should be loaded from a different folder.

You were right. After changing the content root folder to the folder where my IDE points, I no longer see the issue. Thanks!
