### ISSUE TITLE
Detecting File Changes in Docker

### ISSUE THREAD

**Issue by tonysneed** [aspnet/dotnet-watch#91]
Dnx-watch required the following entry in a Dockerfile in order to detect file changes:

```dockerfile
ENV MONO_MANAGED_WATCHER 1
```

Is there a replacement for this in `dotnet watch`?  Currently it does not detect file changes when running in a Docker container.  See my repo here for an example: https://github.com/tonysneed/Demo.DotNetWatchDocker

**Comment by victorhurdugaci** [comment]
That's a known limitation. The corefx watcher doesn't trigger property in all cases. Use the polling watcher instead by setting `USE_POLLING_FILE_WATCHER=1`.

We'll add it to the documentation soon.

**Comment by tonysneed** [comment]
Thanks, exactly what I was looking for.

**Comment by vinaydate** [comment]
Worked for me as well. Thanks

**Comment by victorhurdugaci** [comment]
Please note that in the latest version (from the `dev` branch) we've renamed the variable: https://github.com/aspnet/Announcements/issues/186
