### ISSUE TITLE
Configuration argument to 'run' not taking affect

### ISSUE THREAD

**Issue by kichalla** [aspnet/dotnet-watch#94]
Repro:
- do a `dotnet watch` on an app. This will by default compile the target app in `debug` mode.
- Ctrl + C to kill the dotnet watch
- do a `dotnet watch --run -c Release` and you should see this not building the app for Release

```
C:\temp\DotnetWatchTestApp\src\ConsoleApp [master]> dotnet --info
.NET Command Line Tools (1.0.0-rc2-002659)

Product Information:
 Version:     1.0.0-rc2-002659
 Commit Sha:  11a001706f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by victorhurdugaci** [comment]
You command is incorrect. You should run

`dotnet watch --command run -- -c Release`

because 

`dotnet watch --run -c Release` becomes

`dotnet run --run -c Release`

**Comment by kichalla** [comment]
Ah yes. My bad. I verified it now and it works.
