### ISSUE TITLE
error using dotnet watch

### ISSUE THREAD

**Issue by Bartmax** [aspnet/dotnet-watch#97]
Could not read the incremental cache file: ...

Not sure what is this, but a proper error message telling me how to fix it will surely help.
is this a bug on the watcher or something wrong with my code?

**Comment by victorhurdugaci** [comment]
Please share more details about what you were doing when you got that error. Project files, executed command, dotnet version would be useful

**Comment by Bartmax** [comment]
@victorhurdugaci I understand that the info provided is poor, unfortunately i'm not sure what was exactly what happened.

I can provide little info, unless until I get that error again.

I had a working solution,
run dotnet watch
did a lot of changes, specially on model objects (ef entities), had to upgrade database, execute migrations, lots of breaking stuff on controllers/services etc. Somewhere in between the dotnet watch were returning that error and when I get the project to compile successfully again the error was persisted. Had to close and reopen dotnet watch and had same error.

I can't be sure what exactly fixed the issue as I deleted obj/bin folders, clear nuget packages cache, restore again and the it worked. 

It was in the middle of a rc1->rc2 migration, there were too many moving parts.

Didn't see the error again. I know this is not of much help... If I ever get this error I will try to be more 'debuging' and less 'try to fix'.

When I filed the issue, I was thinking that the error can be understood by MS developers and maybe apply a proper error message and some info about what this is and a way to fix it. Like (delete obj/bin folders and try again, if it has anything to do with the error, of course.)

**Comment by victorhurdugaci** [comment]
I've never seen that message before but I searched for it now. It seems to be coming from dotnet cli https://github.com/dotnet/cli/blob/91fb67835d11f60bbe4763f0de6d3859236cb07a/src/dotnet/commands/dotnet-build/IncrementalCache.cs 

It was probably a build bug. I suggest opening a bug on the CLI if you see it again.

**Comment by Bartmax** [comment]
Sure. Feel free to close this as I understand is not of much help.
