### ISSUE TITLE
NoDepsAppTests.RestartProcessThatTerminatesAfterFileChange needs to be more resilient

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dotnet-watch#98]
```
System.Exception : Process did not restart because D:\b\w\e70224f4ea5e88a1\dotnet-watch\testWorkDir\ab30856d-c17a-4d4f-8800-65492700357b\status.started was not changed
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTests.RestartProcessThatTerminatesAfterFileChange() in D:\b\w\e70224f4ea5e88a1\dotnet-watch\test\Microsoft.DotNet.Watcher.Tools.FunctionalTests\NoDepsAppTests.cs:line 57
```

The test has a success rate of 95.7% and passes on retry.

**Comment by dougbu** [comment]
This test doesn't always pass on retries and is one of the reasons our Test passes are frequently red. ~95% success isn't good enough.

@muratg any objection to temporarily disabling this test until someone can address the root cause?

**Comment by muratg** [comment]
@dougbu yes, please do!

@victorhurdugaci could you please investigate?

**Comment by dougbu** [comment]
Revert dc9fead as part of this fix.
